{% set name = "awscrt" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awscrt-{{ version }}.tar.gz
  sha256: 3062d315cb16542fe04dd8239f2e8bc3238ee9045cd5070b915cf2ebbecbaaac
  patches:
    - 0001-Use-aws-libs-from-PREFIX.patch
    - 0002-Remove-Werror-from-compile-arguments.patch

build:
  number: 5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - s2n  # [linux]
    - aws-checksums
    - aws-c-common
    - aws-c-cal
    - aws-c-io
    - aws-c-event-stream
    - aws-c-http
    - aws-c-auth
    - aws-c-mqtt
    - aws-c-s3
  run:
    - python

test:
  imports:
    - awscrt
    - awscrt.eventstream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-crt-python
  summary: A common runtime for AWS Python projects
  license: Apache-2.0
  license_file: crt/s2n/LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xhochy
