{% set version = "0.21.5" %}


package:
  name: awscrt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/awscrt/awscrt-{{ version }}.tar.gz
  sha256: 7ec2a67af30fbf386494df00bbdf996f7024000df6b01ab160014afef2b91005
  patches:
    - 0001-Don-t-force-static-linkage.patch

build:
  number: 6

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - s2n  # [linux]
    - aws-checksums
    - aws-c-common
    - aws-c-cal
    - aws-c-io
    - aws-c-event-stream
    - aws-c-http
    - aws-c-auth
    - aws-c-mqtt
    - aws-c-s3
  run:
    - python

test:
  imports:
    - awscrt
    - awscrt.eventstream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-crt-python
  summary: A common runtime for AWS Python projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
    - ocefpaf
    - xhochy
