schema_version: 1

context:
  version: "0.29.2"

package:
  name: awscrt
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/awscrt/awscrt-${{ version }}.tar.gz
  sha256: c78d81b1308d42fda1eb21d27fcf26579137b821043e528550f2cfc6c09ab9ff
  patches:
    - 0001-Don-t-force-static-linkage.patch

build:
  number: 1

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: win
      then: nasm
  host:
    - python
    - pip
    - setuptools
    - if: linux
      then: s2n
    - aws-checksums
    - aws-c-common
    - aws-c-cal
    - aws-c-io
    - aws-c-event-stream
    - aws-c-http
    - aws-c-auth
    - aws-c-mqtt
    - aws-c-s3
  run:
    - python

tests:
  - python:
      imports:
        - awscrt
        - awscrt.eventstream
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: A common runtime for AWS Python projects
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/awslabs/aws-crt-python

extra:
  recipe-maintainers:
    - ocefpaf
    - xhochy
